version: "3.9"
services:
  backend:
    build: ./backend
    expose:
      - "5000"       

  frontend:
    build: ./frontend  
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

